### ISSUE TITLE
Scope Management Tasks

### ISSUE THREAD

**Issue by shakedmanes** [meateam/SpikeServer#4]
### Todo
- [x] Create scope model.
- [x] Implement fuzzy search on clients collections for searching clients.
  - [x] Updating all documents for using fuzzy search (add indexes and hint fields) for each first run (Or maybe create handy script for it)
- [x] Scope model CRUD requests using [meateam/OSpike](https://github.com/meateam/OSpike) API
